### ISSUE TITLE
[Dev Feature] Adding Config Not working

### ISSUE THREAD

**Issue by ai-nikolai** [Wluper/matilda#24]
05/12/2021 04:03:06 PM Exception on /configuration/intuit [PUT]
,Traceback (most recent call last):
,  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
,    response = self.full_dispatch_request()
,  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
,    rv = self.handle_user_exception(e)
,  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
,    return cors_after_request(app.make_response(f(*args, **kwargs)))
,  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
,    reraise(exc_type, exc_value, tb)
,  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
,    raise value
,  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
,    rv = self.dispatch_request()
,  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
,    return self.view_functions[rule.endpoint](**req.view_args)
,  File "/app/server/matilda_app.py", line 153, in handle_configuration_file
,    newFile = json.loads(newFile)
,  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
,    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
,TypeError: the JSON object must be str, bytes or bytearray, not dict

**Comment by ai-nikolai** [comment]
@davivcu Hi Davide,

The feature about adding configs gets the following error, when trying to save a new config file.

**Comment by davivcu** [comment]
Hello,
thanks for letting me know.
I just pushed a commit that fixes the bug.

**Comment by ai-nikolai** [comment]
PR 25 fixed the issue:
https://github.com/Wluper/matilda/pull/25
