### ISSUE TITLE
Error. This could be caused by a server error or a wrong character in your collection file

### ISSUE THREAD

**Issue by unikcc** [Wluper/matilda#30]
I just create collection by add from the example data, dummy_data.json, Then it throwed such error 
![image](https://user-images.githubusercontent.com/19505579/146554819-59d9efb6-7911-4696-961e-14beeafc0ada.png)

**Comment by unikcc** [comment]
Solved. Key of json can't contains ".".

**Comment by alex-berman** [comment]
According to the readme, dummy_data.json is an "example of data in the correct form". Is it not, then?
